image: ruby:2.5

variables:
  BUNDLE_PATH: vendor/bundle

cache:
  key: gems
  paths:
    - vendor/bundle

before_script:
  - ruby -v
  - bundle -v

stages:
  - prepare
  - test
  - build

prepare:
  stage: prepare
  script:
    - bundle install --jobs $(nproc) "${FLAGS[@]}"
    - bundle clean --force
  tags:
    - openshift

audit:
  stage: prepare
  script:
    - gem install bundler-audit
    - bundle audit check --update
  allow_failure: true
  cache:
  tags:
    - openshift

test:
  stage: test
  script:
    - bundle exec rspec
  cache:
    key: gems
    paths:
      - vendor/bundle
    policy: pull
  tags:
    - openshift

build:
  only:
    - tags
  stage: build
  cache:
    key: gems
    paths:
      - vendor/bundle
    policy: pull
  artifacts:
    paths:
      - '*.gem'
  script:
    - push-gems
  tags:
    - gem
